dist: xenial
language: python
python:
  - 3.7.2
  - 3.8
before_install:
  - pip install -r requirements-test.txt
install:
  - ls -l
  - pip uninstall whatstk
  - pip install -e .
#pip install -r requirements.txt 
script:
  - pip freeze | grep whatstk
  - pytest --cov-report term --cov=whatstk tests/
after_success:
  - codecov # submit coverage
deploy:
  provider: pypi
  user: $USER_PYPI
  password: $PWD_PYPI
  on:
    tags: true
